spring:
  datasource:
      url: jdbc:mysql://localhost:3306/spring_security?useSSL=false&characterEncoding=utf-8
      username: root
      password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect